#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker build -f $DIR/Dockerfile \
             -t openstax/swagger-ruby:latest \
             --build-arg bundler_version=2.2.4 \
             $DIR/..
